# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: command.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='command.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\rcommand.proto\x1a\x0c\x63ommon.proto\"$\n\tMoveToPos\x12\x17\n\x07\x64\x65stPos\x18\x01 \x02(\x0b\x32\x06.VInt3\".\n\x0c\x41ttackCommon\x12\x0f\n\x07\x61\x63torID\x18\x01 \x02(\r\x12\r\n\x05start\x18\x02 \x02(\x05\"N\n\x08ObjSkill\x12\x0f\n\x07skillID\x18\x01 \x02(\r\x12\x0f\n\x07\x61\x63torID\x18\x02 \x02(\r\x12 \n\x08slotType\x18\x03 \x02(\x0e\x32\x0e.SkillSlotType\"^\n\x08\x44irSkill\x12\x0f\n\x07skillID\x18\x01 \x02(\r\x12\x0f\n\x07\x61\x63torID\x18\x02 \x02(\r\x12 \n\x08slotType\x18\x03 \x02(\x0e\x32\x0e.SkillSlotType\x12\x0e\n\x06\x64\x65gree\x18\x04 \x02(\x05\"V\n\x08PosSkill\x12\x0f\n\x07skillID\x18\x01 \x02(\r\x12\x17\n\x07\x64\x65stPos\x18\x02 \x02(\x0b\x32\x06.VInt3\x12 \n\x08slotType\x18\x03 \x02(\x0e\x32\x0e.SkillSlotType\".\n\x0bTalentSkill\x12\x0e\n\x06\x64\x65gree\x18\x01 \x01(\x05\x12\x0f\n\x07\x61\x63torID\x18\x02 \x02(\r\"\xee\x01\n\x06\x43mdPkg\x12\"\n\x0c\x63ommand_type\x18\x01 \x02(\x0e\x32\x0c.CommandType\x12\x1c\n\x08move_pos\x18\x02 \x01(\x0b\x32\n.MoveToPos\x12$\n\rattack_common\x18\x03 \x01(\x0b\x32\r.AttackCommon\x12\x1c\n\tobj_skill\x18\x04 \x01(\x0b\x32\t.ObjSkill\x12\x1c\n\tdir_skill\x18\x05 \x01(\x0b\x32\t.DirSkill\x12\x1c\n\tpos_skill\x18\x06 \x01(\x0b\x32\t.PosSkill\x12\"\n\x0ctalent_skill\x18\x07 \x01(\x0b\x32\x0c.TalentSkill\"<\n\rAICommandInfo\x12\x10\n\x08\x61\x63tor_id\x18\x01 \x02(\x05\x12\x19\n\x08\x63md_info\x18\x02 \x01(\x0b\x32\x07.CmdPkg*\xcc\x01\n\x0b\x43ommandType\x12\x15\n\x11\x43OMMAND_TYPE_None\x10\x00\x12\x18\n\x14\x43OMMAND_TYPE_MovePos\x10\x01\x12\x1d\n\x19\x43OMMAND_TYPE_AttackCommon\x10\x02\x12\x19\n\x15\x43OMMAND_TYPE_ObjSkill\x10\x03\x12\x19\n\x15\x43OMMAND_TYPE_DirSkill\x10\x04\x12\x19\n\x15\x43OMMAND_TYPE_PosSkill\x10\x05\x12\x1c\n\x18\x43OMMAND_TYPE_TalentSkill\x10\x06')
  ,
  dependencies=[common__pb2.DESCRIPTOR,])

_COMMANDTYPE = _descriptor.EnumDescriptor(
  name='CommandType',
  full_name='CommandType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COMMAND_TYPE_None', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMMAND_TYPE_MovePos', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMMAND_TYPE_AttackCommon', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMMAND_TYPE_ObjSkill', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMMAND_TYPE_DirSkill', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMMAND_TYPE_PosSkill', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='COMMAND_TYPE_TalentSkill', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=733,
  serialized_end=937,
)
_sym_db.RegisterEnumDescriptor(_COMMANDTYPE)

CommandType = enum_type_wrapper.EnumTypeWrapper(_COMMANDTYPE)
COMMAND_TYPE_None = 0
COMMAND_TYPE_MovePos = 1
COMMAND_TYPE_AttackCommon = 2
COMMAND_TYPE_ObjSkill = 3
COMMAND_TYPE_DirSkill = 4
COMMAND_TYPE_PosSkill = 5
COMMAND_TYPE_TalentSkill = 6



_MOVETOPOS = _descriptor.Descriptor(
  name='MoveToPos',
  full_name='MoveToPos',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='destPos', full_name='MoveToPos.destPos', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=67,
)


_ATTACKCOMMON = _descriptor.Descriptor(
  name='AttackCommon',
  full_name='AttackCommon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='actorID', full_name='AttackCommon.actorID', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start', full_name='AttackCommon.start', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=115,
)


_OBJSKILL = _descriptor.Descriptor(
  name='ObjSkill',
  full_name='ObjSkill',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='skillID', full_name='ObjSkill.skillID', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actorID', full_name='ObjSkill.actorID', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='slotType', full_name='ObjSkill.slotType', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=117,
  serialized_end=195,
)


_DIRSKILL = _descriptor.Descriptor(
  name='DirSkill',
  full_name='DirSkill',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='skillID', full_name='DirSkill.skillID', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actorID', full_name='DirSkill.actorID', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='slotType', full_name='DirSkill.slotType', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='degree', full_name='DirSkill.degree', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=291,
)


_POSSKILL = _descriptor.Descriptor(
  name='PosSkill',
  full_name='PosSkill',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='skillID', full_name='PosSkill.skillID', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destPos', full_name='PosSkill.destPos', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='slotType', full_name='PosSkill.slotType', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=293,
  serialized_end=379,
)


_TALENTSKILL = _descriptor.Descriptor(
  name='TalentSkill',
  full_name='TalentSkill',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='degree', full_name='TalentSkill.degree', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='actorID', full_name='TalentSkill.actorID', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=381,
  serialized_end=427,
)


_CMDPKG = _descriptor.Descriptor(
  name='CmdPkg',
  full_name='CmdPkg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command_type', full_name='CmdPkg.command_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='move_pos', full_name='CmdPkg.move_pos', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='attack_common', full_name='CmdPkg.attack_common', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='obj_skill', full_name='CmdPkg.obj_skill', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dir_skill', full_name='CmdPkg.dir_skill', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos_skill', full_name='CmdPkg.pos_skill', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='talent_skill', full_name='CmdPkg.talent_skill', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=430,
  serialized_end=668,
)


_AICOMMANDINFO = _descriptor.Descriptor(
  name='AICommandInfo',
  full_name='AICommandInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='actor_id', full_name='AICommandInfo.actor_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cmd_info', full_name='AICommandInfo.cmd_info', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=670,
  serialized_end=730,
)

_MOVETOPOS.fields_by_name['destPos'].message_type = common__pb2._VINT3
_OBJSKILL.fields_by_name['slotType'].enum_type = common__pb2._SKILLSLOTTYPE
_DIRSKILL.fields_by_name['slotType'].enum_type = common__pb2._SKILLSLOTTYPE
_POSSKILL.fields_by_name['destPos'].message_type = common__pb2._VINT3
_POSSKILL.fields_by_name['slotType'].enum_type = common__pb2._SKILLSLOTTYPE
_CMDPKG.fields_by_name['command_type'].enum_type = _COMMANDTYPE
_CMDPKG.fields_by_name['move_pos'].message_type = _MOVETOPOS
_CMDPKG.fields_by_name['attack_common'].message_type = _ATTACKCOMMON
_CMDPKG.fields_by_name['obj_skill'].message_type = _OBJSKILL
_CMDPKG.fields_by_name['dir_skill'].message_type = _DIRSKILL
_CMDPKG.fields_by_name['pos_skill'].message_type = _POSSKILL
_CMDPKG.fields_by_name['talent_skill'].message_type = _TALENTSKILL
_AICOMMANDINFO.fields_by_name['cmd_info'].message_type = _CMDPKG
DESCRIPTOR.message_types_by_name['MoveToPos'] = _MOVETOPOS
DESCRIPTOR.message_types_by_name['AttackCommon'] = _ATTACKCOMMON
DESCRIPTOR.message_types_by_name['ObjSkill'] = _OBJSKILL
DESCRIPTOR.message_types_by_name['DirSkill'] = _DIRSKILL
DESCRIPTOR.message_types_by_name['PosSkill'] = _POSSKILL
DESCRIPTOR.message_types_by_name['TalentSkill'] = _TALENTSKILL
DESCRIPTOR.message_types_by_name['CmdPkg'] = _CMDPKG
DESCRIPTOR.message_types_by_name['AICommandInfo'] = _AICOMMANDINFO
DESCRIPTOR.enum_types_by_name['CommandType'] = _COMMANDTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MoveToPos = _reflection.GeneratedProtocolMessageType('MoveToPos', (_message.Message,), dict(
  DESCRIPTOR = _MOVETOPOS,
  __module__ = 'command_pb2'
  # @@protoc_insertion_point(class_scope:MoveToPos)
  ))
_sym_db.RegisterMessage(MoveToPos)

AttackCommon = _reflection.GeneratedProtocolMessageType('AttackCommon', (_message.Message,), dict(
  DESCRIPTOR = _ATTACKCOMMON,
  __module__ = 'command_pb2'
  # @@protoc_insertion_point(class_scope:AttackCommon)
  ))
_sym_db.RegisterMessage(AttackCommon)

ObjSkill = _reflection.GeneratedProtocolMessageType('ObjSkill', (_message.Message,), dict(
  DESCRIPTOR = _OBJSKILL,
  __module__ = 'command_pb2'
  # @@protoc_insertion_point(class_scope:ObjSkill)
  ))
_sym_db.RegisterMessage(ObjSkill)

DirSkill = _reflection.GeneratedProtocolMessageType('DirSkill', (_message.Message,), dict(
  DESCRIPTOR = _DIRSKILL,
  __module__ = 'command_pb2'
  # @@protoc_insertion_point(class_scope:DirSkill)
  ))
_sym_db.RegisterMessage(DirSkill)

PosSkill = _reflection.GeneratedProtocolMessageType('PosSkill', (_message.Message,), dict(
  DESCRIPTOR = _POSSKILL,
  __module__ = 'command_pb2'
  # @@protoc_insertion_point(class_scope:PosSkill)
  ))
_sym_db.RegisterMessage(PosSkill)

TalentSkill = _reflection.GeneratedProtocolMessageType('TalentSkill', (_message.Message,), dict(
  DESCRIPTOR = _TALENTSKILL,
  __module__ = 'command_pb2'
  # @@protoc_insertion_point(class_scope:TalentSkill)
  ))
_sym_db.RegisterMessage(TalentSkill)

CmdPkg = _reflection.GeneratedProtocolMessageType('CmdPkg', (_message.Message,), dict(
  DESCRIPTOR = _CMDPKG,
  __module__ = 'command_pb2'
  # @@protoc_insertion_point(class_scope:CmdPkg)
  ))
_sym_db.RegisterMessage(CmdPkg)

AICommandInfo = _reflection.GeneratedProtocolMessageType('AICommandInfo', (_message.Message,), dict(
  DESCRIPTOR = _AICOMMANDINFO,
  __module__ = 'command_pb2'
  # @@protoc_insertion_point(class_scope:AICommandInfo)
  ))
_sym_db.RegisterMessage(AICommandInfo)


# @@protoc_insertion_point(module_scope)
