# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scene.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='scene.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0bscene.proto\x1a\x0c\x63ommon.proto\"\x9c\x01\n\x06\x42ullet\x12\x12\n\nruntime_id\x18\x01 \x02(\x05\x12\x19\n\x04\x63\x61mp\x18\x02 \x01(\x0e\x32\x0b.PlayerCamp\x12\x14\n\x0csource_actor\x18\x03 \x02(\x05\x12!\n\tslot_type\x18\x04 \x01(\x0e\x32\x0e.SkillSlotType\x12\x10\n\x08skill_id\x18\x05 \x02(\x05\x12\x18\n\x08location\x18\x06 \x02(\x0b\x32\x06.VInt3')
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_BULLET = _descriptor.Descriptor(
  name='Bullet',
  full_name='Bullet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='runtime_id', full_name='Bullet.runtime_id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='camp', full_name='Bullet.camp', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source_actor', full_name='Bullet.source_actor', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='slot_type', full_name='Bullet.slot_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='skill_id', full_name='Bullet.skill_id', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='Bullet.location', index=5,
      number=6, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=186,
)

_BULLET.fields_by_name['camp'].enum_type = common__pb2._PLAYERCAMP
_BULLET.fields_by_name['slot_type'].enum_type = common__pb2._SKILLSLOTTYPE
_BULLET.fields_by_name['location'].message_type = common__pb2._VINT3
DESCRIPTOR.message_types_by_name['Bullet'] = _BULLET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Bullet = _reflection.GeneratedProtocolMessageType('Bullet', (_message.Message,), dict(
  DESCRIPTOR = _BULLET,
  __module__ = 'scene_pb2'
  # @@protoc_insertion_point(class_scope:Bullet)
  ))
_sym_db.RegisterMessage(Bullet)


# @@protoc_insertion_point(module_scope)
