# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sgame_ai_server.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import command_pb2 as command__pb2
from . import sgame_state_pb2 as sgame__state__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sgame_ai_server.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x15sgame_ai_server.proto\x1a\rcommand.proto\x1a\x11sgame_state.proto\"0\n\x0cStepFrameReq\x12 \n\x0b\x66rame_state\x18\x01 \x02(\x0b\x32\x0b.FrameState\"L\n\x0cStepFrameRsp\x12 \n\x08\x63md_list\x18\x01 \x03(\x0b\x32\x0e.AICommandInfo\x12\x1a\n\x12gameover_ai_server\x18\x02 \x01(\x05\"\x0f\n\rFightStartReq\"\x0f\n\rFightStartRsp\"&\n\x0c\x46ightOverReq\x12\x16\n\x0egameover_state\x18\x01 \x01(\x05\"\x0e\n\x0c\x46ightOverRsp')
  ,
  dependencies=[command__pb2.DESCRIPTOR,sgame__state__pb2.DESCRIPTOR,])




_STEPFRAMEREQ = _descriptor.Descriptor(
  name='StepFrameReq',
  full_name='StepFrameReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_state', full_name='StepFrameReq.frame_state', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=107,
)


_STEPFRAMERSP = _descriptor.Descriptor(
  name='StepFrameRsp',
  full_name='StepFrameRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd_list', full_name='StepFrameRsp.cmd_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gameover_ai_server', full_name='StepFrameRsp.gameover_ai_server', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=185,
)


_FIGHTSTARTREQ = _descriptor.Descriptor(
  name='FightStartReq',
  full_name='FightStartReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=202,
)


_FIGHTSTARTRSP = _descriptor.Descriptor(
  name='FightStartRsp',
  full_name='FightStartRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=204,
  serialized_end=219,
)


_FIGHTOVERREQ = _descriptor.Descriptor(
  name='FightOverReq',
  full_name='FightOverReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gameover_state', full_name='FightOverReq.gameover_state', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=259,
)


_FIGHTOVERRSP = _descriptor.Descriptor(
  name='FightOverRsp',
  full_name='FightOverRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=275,
)

_STEPFRAMEREQ.fields_by_name['frame_state'].message_type = sgame__state__pb2._FRAMESTATE
_STEPFRAMERSP.fields_by_name['cmd_list'].message_type = command__pb2._AICOMMANDINFO
DESCRIPTOR.message_types_by_name['StepFrameReq'] = _STEPFRAMEREQ
DESCRIPTOR.message_types_by_name['StepFrameRsp'] = _STEPFRAMERSP
DESCRIPTOR.message_types_by_name['FightStartReq'] = _FIGHTSTARTREQ
DESCRIPTOR.message_types_by_name['FightStartRsp'] = _FIGHTSTARTRSP
DESCRIPTOR.message_types_by_name['FightOverReq'] = _FIGHTOVERREQ
DESCRIPTOR.message_types_by_name['FightOverRsp'] = _FIGHTOVERRSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StepFrameReq = _reflection.GeneratedProtocolMessageType('StepFrameReq', (_message.Message,), dict(
  DESCRIPTOR = _STEPFRAMEREQ,
  __module__ = 'sgame_ai_server_pb2'
  # @@protoc_insertion_point(class_scope:StepFrameReq)
  ))
_sym_db.RegisterMessage(StepFrameReq)

StepFrameRsp = _reflection.GeneratedProtocolMessageType('StepFrameRsp', (_message.Message,), dict(
  DESCRIPTOR = _STEPFRAMERSP,
  __module__ = 'sgame_ai_server_pb2'
  # @@protoc_insertion_point(class_scope:StepFrameRsp)
  ))
_sym_db.RegisterMessage(StepFrameRsp)

FightStartReq = _reflection.GeneratedProtocolMessageType('FightStartReq', (_message.Message,), dict(
  DESCRIPTOR = _FIGHTSTARTREQ,
  __module__ = 'sgame_ai_server_pb2'
  # @@protoc_insertion_point(class_scope:FightStartReq)
  ))
_sym_db.RegisterMessage(FightStartReq)

FightStartRsp = _reflection.GeneratedProtocolMessageType('FightStartRsp', (_message.Message,), dict(
  DESCRIPTOR = _FIGHTSTARTRSP,
  __module__ = 'sgame_ai_server_pb2'
  # @@protoc_insertion_point(class_scope:FightStartRsp)
  ))
_sym_db.RegisterMessage(FightStartRsp)

FightOverReq = _reflection.GeneratedProtocolMessageType('FightOverReq', (_message.Message,), dict(
  DESCRIPTOR = _FIGHTOVERREQ,
  __module__ = 'sgame_ai_server_pb2'
  # @@protoc_insertion_point(class_scope:FightOverReq)
  ))
_sym_db.RegisterMessage(FightOverReq)

FightOverRsp = _reflection.GeneratedProtocolMessageType('FightOverRsp', (_message.Message,), dict(
  DESCRIPTOR = _FIGHTOVERRSP,
  __module__ = 'sgame_ai_server_pb2'
  # @@protoc_insertion_point(class_scope:FightOverRsp)
  ))
_sym_db.RegisterMessage(FightOverRsp)


# @@protoc_insertion_point(module_scope)
